// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Park_Direct,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.450000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=4,HLS_SYN_FF=533,HLS_SYN_LUT=211}" *)

module Park_Direct (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_V_TDATA,
        s_axis_V_TVALID,
        s_axis_V_TREADY,
        m_axis_V_TDATA,
        m_axis_V_TVALID,
        m_axis_V_TREADY,
        Id_out,
        Id_out_ap_vld,
        Iq_out,
        Iq_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] s_axis_V_TDATA;
input   s_axis_V_TVALID;
output   s_axis_V_TREADY;
output  [63:0] m_axis_V_TDATA;
output   m_axis_V_TVALID;
input   m_axis_V_TREADY;
output  [31:0] Id_out;
output   Id_out_ap_vld;
output  [31:0] Iq_out;
output   Iq_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Id_out_ap_vld;
reg Iq_out_ap_vld;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] s_axis_V_0_data_out;
wire    s_axis_V_0_vld_in;
wire    s_axis_V_0_vld_out;
wire    s_axis_V_0_ack_in;
reg    s_axis_V_0_ack_out;
reg   [63:0] s_axis_V_0_payload_A;
reg   [63:0] s_axis_V_0_payload_B;
reg    s_axis_V_0_sel_rd;
reg    s_axis_V_0_sel_wr;
wire    s_axis_V_0_sel;
wire    s_axis_V_0_load_A;
wire    s_axis_V_0_load_B;
reg   [1:0] s_axis_V_0_state;
wire    s_axis_V_0_state_cmp_full;
reg   [63:0] m_axis_V_1_data_out;
reg    m_axis_V_1_vld_in;
wire    m_axis_V_1_vld_out;
wire    m_axis_V_1_ack_in;
wire    m_axis_V_1_ack_out;
reg   [63:0] m_axis_V_1_payload_A;
reg   [63:0] m_axis_V_1_payload_B;
reg    m_axis_V_1_sel_rd;
reg    m_axis_V_1_sel_wr;
wire    m_axis_V_1_sel;
wire    m_axis_V_1_load_A;
wire    m_axis_V_1_load_B;
reg   [1:0] m_axis_V_1_state;
wire    m_axis_V_1_state_cmp_full;
wire   [9:0] cos_table_address0;
reg    cos_table_ce0;
wire   [15:0] cos_table_q0;
wire   [9:0] sin_table_address0;
reg    sin_table_ce0;
wire   [15:0] sin_table_q0;
reg    s_axis_V_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg    m_axis_V_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [15:0] Ialpha_fu_119_p1;
reg  signed [15:0] Ialpha_reg_315;
reg  signed [15:0] Ibeta_reg_320;
reg   [31:0] tmp_10_reg_335;
reg   [15:0] cos_table_load_reg_340;
wire    ap_CS_fsm_state3;
reg   [15:0] sin_table_load_reg_345;
wire  signed [31:0] tmp_5_fu_162_p1;
reg  signed [31:0] tmp_5_reg_350;
wire    ap_CS_fsm_state4;
wire  signed [31:0] Ia_cos_fu_287_p2;
reg  signed [31:0] Ia_cos_reg_355;
wire  signed [31:0] tmp_6_fu_165_p1;
reg  signed [31:0] tmp_6_reg_360;
wire  signed [31:0] Ib_cos_fu_293_p2;
reg  signed [31:0] Ib_cos_reg_365;
reg   [16:0] tmp_1_reg_370;
wire    ap_CS_fsm_state5;
reg   [16:0] tmp_2_reg_375;
wire   [0:0] icmp_fu_198_p2;
reg   [0:0] icmp_reg_380;
wire   [0:0] icmp3_fu_213_p2;
reg   [0:0] icmp3_reg_385;
wire   [63:0] res_fu_277_p4;
wire  signed [31:0] tmp_4_fu_143_p1;
reg    ap_reg_ioackin_Id_out_dummy_ack;
reg    ap_reg_ioackin_Iq_out_dummy_ack;
wire   [15:0] Theta_fu_133_p4;
wire  signed [31:0] grp_fu_299_p3;
wire  signed [31:0] grp_fu_307_p3;
wire   [1:0] tmp_fu_189_p4;
wire   [1:0] tmp_12_fu_204_p4;
wire   [16:0] Id_fu_219_p3;
wire   [0:0] tmp_8_fu_229_p2;
wire   [15:0] tmp_3_fu_225_p1;
wire   [15:0] Id_1_fu_235_p3;
wire   [16:0] Iq_fu_248_p3;
wire   [0:0] tmp_s_fu_258_p2;
wire   [15:0] tmp_13_fu_254_p1;
wire   [15:0] Iq_1_fu_264_p3;
wire  signed [15:0] Ia_cos_fu_287_p0;
wire  signed [31:0] cos_theta_fu_159_p1;
wire  signed [15:0] Ib_cos_fu_293_p0;
wire  signed [15:0] grp_fu_299_p0;
wire  signed [15:0] grp_fu_299_p1;
wire  signed [31:0] sin_theta_fu_168_p1;
wire  signed [15:0] grp_fu_307_p0;
wire  signed [15:0] grp_fu_307_p1;
reg   [6:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 s_axis_V_0_sel_rd = 1'b0;
#0 s_axis_V_0_sel_wr = 1'b0;
#0 s_axis_V_0_state = 2'd0;
#0 m_axis_V_1_sel_rd = 1'b0;
#0 m_axis_V_1_sel_wr = 1'b0;
#0 m_axis_V_1_state = 2'd0;
#0 ap_reg_ioackin_Id_out_dummy_ack = 1'b0;
#0 ap_reg_ioackin_Iq_out_dummy_ack = 1'b0;
end

Park_Direct_cos_tbkb #(
    .DataWidth( 16 ),
    .AddressRange( 1000 ),
    .AddressWidth( 10 ))
cos_table_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(cos_table_address0),
    .ce0(cos_table_ce0),
    .q0(cos_table_q0)
);

Park_Direct_sin_tcud #(
    .DataWidth( 16 ),
    .AddressRange( 1000 ),
    .AddressWidth( 10 ))
sin_table_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sin_table_address0),
    .ce0(sin_table_ce0),
    .q0(sin_table_q0)
);

Park_Direct_mul_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Park_Direct_mul_mdEe_U0(
    .din0(Ia_cos_fu_287_p0),
    .din1(Ialpha_reg_315),
    .dout(Ia_cos_fu_287_p2)
);

Park_Direct_mul_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Park_Direct_mul_mdEe_U1(
    .din0(Ib_cos_fu_293_p0),
    .din1(Ibeta_reg_320),
    .dout(Ib_cos_fu_293_p2)
);

Park_Direct_mac_meOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Park_Direct_mac_meOg_U2(
    .din0(grp_fu_299_p0),
    .din1(grp_fu_299_p1),
    .din2(Ia_cos_reg_355),
    .dout(grp_fu_299_p3)
);

Park_Direct_mac_mfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Park_Direct_mac_mfYi_U3(
    .din0(grp_fu_307_p0),
    .din1(grp_fu_307_p1),
    .din2(Ib_cos_reg_365),
    .dout(grp_fu_307_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_Id_out_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            if ((m_axis_V_1_ack_in == 1'b1)) begin
                ap_reg_ioackin_Id_out_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_Id_out_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_Iq_out_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            if ((m_axis_V_1_ack_in == 1'b1)) begin
                ap_reg_ioackin_Iq_out_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_Iq_out_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == m_axis_V_1_ack_out) & (1'b1 == m_axis_V_1_vld_out))) begin
            m_axis_V_1_sel_rd <= ~m_axis_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == m_axis_V_1_vld_in) & (1'b1 == m_axis_V_1_ack_in))) begin
            m_axis_V_1_sel_wr <= ~m_axis_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        m_axis_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == m_axis_V_1_vld_in) & (1'b1 == m_axis_V_1_ack_out) & (2'd3 == m_axis_V_1_state)) | ((1'b0 == m_axis_V_1_vld_in) & (2'd2 == m_axis_V_1_state)))) begin
            m_axis_V_1_state <= 2'd2;
        end else if ((((1'b1 == m_axis_V_1_vld_in) & (1'b0 == m_axis_V_1_ack_out) & (2'd3 == m_axis_V_1_state)) | ((1'b0 == m_axis_V_1_ack_out) & (2'd1 == m_axis_V_1_state)))) begin
            m_axis_V_1_state <= 2'd1;
        end else if ((((1'b1 == m_axis_V_1_vld_in) & (2'd2 == m_axis_V_1_state)) | ((1'b1 == m_axis_V_1_ack_out) & (2'd1 == m_axis_V_1_state)) | ((2'd3 == m_axis_V_1_state) & ~((1'b1 == m_axis_V_1_vld_in) & (1'b0 == m_axis_V_1_ack_out)) & ~((1'b0 == m_axis_V_1_vld_in) & (1'b1 == m_axis_V_1_ack_out))))) begin
            m_axis_V_1_state <= 2'd3;
        end else begin
            m_axis_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        s_axis_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == s_axis_V_0_ack_out) & (1'b1 == s_axis_V_0_vld_out))) begin
            s_axis_V_0_sel_rd <= ~s_axis_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        s_axis_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == s_axis_V_0_vld_in) & (1'b1 == s_axis_V_0_ack_in))) begin
            s_axis_V_0_sel_wr <= ~s_axis_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        s_axis_V_0_state <= 2'd0;
    end else begin
        if ((((1'b0 == s_axis_V_0_vld_in) & (1'b1 == s_axis_V_0_ack_out) & (s_axis_V_0_state == 2'd3)) | ((1'b0 == s_axis_V_0_vld_in) & (s_axis_V_0_state == 2'd2)))) begin
            s_axis_V_0_state <= 2'd2;
        end else if ((((1'b1 == s_axis_V_0_vld_in) & (1'b0 == s_axis_V_0_ack_out) & (s_axis_V_0_state == 2'd3)) | ((1'b0 == s_axis_V_0_ack_out) & (s_axis_V_0_state == 2'd1)))) begin
            s_axis_V_0_state <= 2'd1;
        end else if ((((1'b1 == s_axis_V_0_vld_in) & (s_axis_V_0_state == 2'd2)) | ((1'b1 == s_axis_V_0_ack_out) & (s_axis_V_0_state == 2'd1)) | ((s_axis_V_0_state == 2'd3) & ~((1'b1 == s_axis_V_0_vld_in) & (1'b0 == s_axis_V_0_ack_out)) & ~((1'b0 == s_axis_V_0_vld_in) & (1'b1 == s_axis_V_0_ack_out))))) begin
            s_axis_V_0_state <= 2'd3;
        end else begin
            s_axis_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Ia_cos_reg_355 <= Ia_cos_fu_287_p2;
        Ib_cos_reg_365 <= Ib_cos_fu_293_p2;
        tmp_5_reg_350 <= tmp_5_fu_162_p1;
        tmp_6_reg_360 <= tmp_6_fu_165_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (s_axis_V_0_vld_out == 1'b1))) begin
        Ialpha_reg_315 <= Ialpha_fu_119_p1;
        Ibeta_reg_320 <= {{s_axis_V_0_data_out[31:16]}};
        tmp_10_reg_335 <= {{s_axis_V_0_data_out[63:32]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cos_table_load_reg_340 <= cos_table_q0;
        sin_table_load_reg_345 <= sin_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp3_reg_385 <= icmp3_fu_213_p2;
        icmp_reg_380 <= icmp_fu_198_p2;
        tmp_1_reg_370 <= {{grp_fu_299_p3[31:15]}};
        tmp_2_reg_375 <= {{grp_fu_307_p3[31:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == m_axis_V_1_load_A)) begin
        m_axis_V_1_payload_A <= res_fu_277_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == m_axis_V_1_load_B)) begin
        m_axis_V_1_payload_B <= res_fu_277_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == s_axis_V_0_load_A)) begin
        s_axis_V_0_payload_A <= s_axis_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == s_axis_V_0_load_B)) begin
        s_axis_V_0_payload_B <= s_axis_V_TDATA;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_reg_ioackin_Id_out_dummy_ack))) begin
        Id_out_ap_vld = 1'b1;
    end else begin
        Id_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_reg_ioackin_Iq_out_dummy_ack))) begin
        Iq_out_ap_vld = 1'b1;
    end else begin
        Iq_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (m_axis_V_1_ack_in == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (m_axis_V_1_ack_in == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (s_axis_V_0_vld_out == 1'b1))) begin
        cos_table_ce0 = 1'b1;
    end else begin
        cos_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == m_axis_V_1_sel)) begin
        m_axis_V_1_data_out = m_axis_V_1_payload_B;
    end else begin
        m_axis_V_1_data_out = m_axis_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (m_axis_V_1_ack_in == 1'b1))) begin
        m_axis_V_1_vld_in = 1'b1;
    end else begin
        m_axis_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7))) begin
        m_axis_V_TDATA_blk_n = m_axis_V_1_state[1'd1];
    end else begin
        m_axis_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (s_axis_V_0_vld_out == 1'b1))) begin
        s_axis_V_0_ack_out = 1'b1;
    end else begin
        s_axis_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == s_axis_V_0_sel)) begin
        s_axis_V_0_data_out = s_axis_V_0_payload_B;
    end else begin
        s_axis_V_0_data_out = s_axis_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_axis_V_TDATA_blk_n = s_axis_V_0_state[1'd0];
    end else begin
        s_axis_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (s_axis_V_0_vld_out == 1'b1))) begin
        sin_table_ce0 = 1'b1;
    end else begin
        sin_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (s_axis_V_0_vld_out == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (m_axis_V_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (m_axis_V_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Ia_cos_fu_287_p0 = cos_theta_fu_159_p1;

assign Ialpha_fu_119_p1 = s_axis_V_0_data_out[15:0];

assign Ib_cos_fu_293_p0 = cos_theta_fu_159_p1;

assign Id_1_fu_235_p3 = ((tmp_8_fu_229_p2[0:0] === 1'b1) ? 16'd32769 : tmp_3_fu_225_p1);

assign Id_fu_219_p3 = ((icmp_reg_380[0:0] === 1'b1) ? 17'd32767 : tmp_1_reg_370);

assign Id_out = $signed(Id_1_fu_235_p3);

assign Iq_1_fu_264_p3 = ((tmp_s_fu_258_p2[0:0] === 1'b1) ? 16'd32769 : tmp_13_fu_254_p1);

assign Iq_fu_248_p3 = ((icmp3_reg_385[0:0] === 1'b1) ? 17'd32767 : tmp_2_reg_375);

assign Iq_out = $signed(Iq_1_fu_264_p3);

assign Theta_fu_133_p4 = {{s_axis_V_0_data_out[63:48]}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cos_table_address0 = tmp_4_fu_143_p1;

assign cos_theta_fu_159_p1 = $signed(cos_table_load_reg_340);

assign grp_fu_299_p0 = tmp_6_reg_360;

assign grp_fu_299_p1 = sin_theta_fu_168_p1;

assign grp_fu_307_p0 = tmp_5_reg_350;

assign grp_fu_307_p1 = sin_theta_fu_168_p1;

assign icmp3_fu_213_p2 = ((tmp_12_fu_204_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_fu_198_p2 = ((tmp_fu_189_p4 == 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_1_ack_in = m_axis_V_1_state[1'd1];

assign m_axis_V_1_ack_out = m_axis_V_TREADY;

assign m_axis_V_1_load_A = (m_axis_V_1_state_cmp_full & ~m_axis_V_1_sel_wr);

assign m_axis_V_1_load_B = (m_axis_V_1_sel_wr & m_axis_V_1_state_cmp_full);

assign m_axis_V_1_sel = m_axis_V_1_sel_rd;

assign m_axis_V_1_state_cmp_full = ((m_axis_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign m_axis_V_1_vld_out = m_axis_V_1_state[1'd0];

assign m_axis_V_TDATA = m_axis_V_1_data_out;

assign m_axis_V_TVALID = m_axis_V_1_state[1'd0];

assign res_fu_277_p4 = {{{tmp_10_reg_335}, {Iq_1_fu_264_p3}}, {Id_1_fu_235_p3}};

assign s_axis_V_0_ack_in = s_axis_V_0_state[1'd1];

assign s_axis_V_0_load_A = (s_axis_V_0_state_cmp_full & ~s_axis_V_0_sel_wr);

assign s_axis_V_0_load_B = (s_axis_V_0_sel_wr & s_axis_V_0_state_cmp_full);

assign s_axis_V_0_sel = s_axis_V_0_sel_rd;

assign s_axis_V_0_state_cmp_full = ((s_axis_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign s_axis_V_0_vld_in = s_axis_V_TVALID;

assign s_axis_V_0_vld_out = s_axis_V_0_state[1'd0];

assign s_axis_V_TREADY = s_axis_V_0_state[1'd1];

assign sin_table_address0 = tmp_4_fu_143_p1;

assign sin_theta_fu_168_p1 = $signed(sin_table_load_reg_345);

assign tmp_12_fu_204_p4 = {{grp_fu_307_p3[31:30]}};

assign tmp_13_fu_254_p1 = Iq_fu_248_p3[15:0];

assign tmp_3_fu_225_p1 = Id_fu_219_p3[15:0];

assign tmp_4_fu_143_p1 = $signed(Theta_fu_133_p4);

assign tmp_5_fu_162_p1 = Ialpha_reg_315;

assign tmp_6_fu_165_p1 = Ibeta_reg_320;

assign tmp_8_fu_229_p2 = (($signed(Id_fu_219_p3) < $signed(17'd98305)) ? 1'b1 : 1'b0);

assign tmp_fu_189_p4 = {{grp_fu_299_p3[31:30]}};

assign tmp_s_fu_258_p2 = (($signed(Iq_fu_248_p3) < $signed(17'd98305)) ? 1'b1 : 1'b0);

endmodule //Park_Direct
